services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "5001:5001"

  frontend-web:
    build: ./frontend-web
    ports:
      - "3000:80"

  frontend-mobile:
    build: ./frontend-mobile
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"

volumes:
  db_data:
