services:
  visor-frontend:
    image: visor-frontend
    container_name: visor-frontend
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - cockpit-net

networks:
  cockpit-net:
    driver: bridge
